//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 25/09/2017 09:26:03
namespace TreatiesService.Countries
{
    
    /// <summary>
    /// There are no comments for PlayersEntities in the schema.
    /// </summary>
    public partial class PlayersEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new PlayersEntities object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public PlayersEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "crm", "TreatiesService.Countries");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("TreatiesService.Countries", global::System.StringComparison.Ordinal))
            {
                return string.Concat("crm.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Countries in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Countries> Countries
        {
            get
            {
                if ((this._Countries == null))
                {
                    this._Countries = base.CreateQuery<Countries>("Countries");
                }
                return this._Countries;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Countries> _Countries;
        /// <summary>
        /// There are no comments for Countries in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCountries(Countries countries)
        {
            base.AddObject("Countries", countries);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"crm\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/edm\"><EntityType" +
                " Name=\"Countries\"><Key><PropertyRef Name=\"id\" /></Key><Property Name=\"id\" Type=\"" +
                "Edm.Guid\" Nullable=\"false\" /><Property Name=\"countryCode2\" Type=\"Edm.String\" Max" +
                "Length=\"2\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"countryCode3\" Ty" +
                "pe=\"Edm.String\" MaxLength=\"3\" FixedLength=\"false\" Unicode=\"true\" /><Property Nam" +
                "e=\"countryNameEn\" Type=\"Edm.String\" MaxLength=\"250\" FixedLength=\"false\" Unicode=" +
                "\"true\" /><Property Name=\"countryNameOfficialEn\" Type=\"Edm.String\" MaxLength=\"250" +
                "\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"countryRegionUn\" Type=\"Ed" +
                "m.String\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"c" +
                "ountryRegionFAO\" Type=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"" +
                "true\" /><Property Name=\"isDeveloping\" Type=\"Edm.Boolean\" /><Property Name=\"isLDC" +
                "\" Type=\"Edm.Boolean\" /><Property Name=\"isSIDS\" Type=\"Edm.Boolean\" /><Property Na" +
                "me=\"preferredLanguage\" Type=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"false\" Uni" +
                "code=\"true\" /></EntityType></Schema><Schema Namespace=\"Players\" xmlns=\"http://sc" +
                "hemas.microsoft.com/ado/2009/11/edm\"><EntityContainer Name=\"PlayersEntities\" m:I" +
                "sDefaultEntityContainer=\"true\" p6:LazyLoadingEnabled=\"true\" xmlns:p6=\"http://sch" +
                "emas.microsoft.com/ado/2009/02/edm/annotation\"><EntitySet Name=\"Countries\" Entit" +
                "yType=\"crm.Countries\" /></EntityContainer></Schema></edmx:DataServices></edmx:Ed" +
                "mx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for crm.Countries in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Countries")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class Countries : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Countries object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Countries CreateCountries(global::System.Guid ID)
        {
            Countries countries = new Countries();
            countries.id = ID;
            return countries;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property countryCode2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string countryCode2
        {
            get
            {
                return this._countryCode2;
            }
            set
            {
                this.OncountryCode2Changing(value);
                this._countryCode2 = value;
                this.OncountryCode2Changed();
                this.OnPropertyChanged("countryCode2");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _countryCode2;
        partial void OncountryCode2Changing(string value);
        partial void OncountryCode2Changed();
        /// <summary>
        /// There are no comments for Property countryCode3 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string countryCode3
        {
            get
            {
                return this._countryCode3;
            }
            set
            {
                this.OncountryCode3Changing(value);
                this._countryCode3 = value;
                this.OncountryCode3Changed();
                this.OnPropertyChanged("countryCode3");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _countryCode3;
        partial void OncountryCode3Changing(string value);
        partial void OncountryCode3Changed();
        /// <summary>
        /// There are no comments for Property countryNameEn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string countryNameEn
        {
            get
            {
                return this._countryNameEn;
            }
            set
            {
                this.OncountryNameEnChanging(value);
                this._countryNameEn = value;
                this.OncountryNameEnChanged();
                this.OnPropertyChanged("countryNameEn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _countryNameEn;
        partial void OncountryNameEnChanging(string value);
        partial void OncountryNameEnChanged();
        /// <summary>
        /// There are no comments for Property countryNameOfficialEn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string countryNameOfficialEn
        {
            get
            {
                return this._countryNameOfficialEn;
            }
            set
            {
                this.OncountryNameOfficialEnChanging(value);
                this._countryNameOfficialEn = value;
                this.OncountryNameOfficialEnChanged();
                this.OnPropertyChanged("countryNameOfficialEn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _countryNameOfficialEn;
        partial void OncountryNameOfficialEnChanging(string value);
        partial void OncountryNameOfficialEnChanged();
        /// <summary>
        /// There are no comments for Property countryRegionUn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string countryRegionUn
        {
            get
            {
                return this._countryRegionUn;
            }
            set
            {
                this.OncountryRegionUnChanging(value);
                this._countryRegionUn = value;
                this.OncountryRegionUnChanged();
                this.OnPropertyChanged("countryRegionUn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _countryRegionUn;
        partial void OncountryRegionUnChanging(string value);
        partial void OncountryRegionUnChanged();
        /// <summary>
        /// There are no comments for Property countryRegionFAO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string countryRegionFAO
        {
            get
            {
                return this._countryRegionFAO;
            }
            set
            {
                this.OncountryRegionFAOChanging(value);
                this._countryRegionFAO = value;
                this.OncountryRegionFAOChanged();
                this.OnPropertyChanged("countryRegionFAO");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _countryRegionFAO;
        partial void OncountryRegionFAOChanging(string value);
        partial void OncountryRegionFAOChanged();
        /// <summary>
        /// There are no comments for Property isDeveloping in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> isDeveloping
        {
            get
            {
                return this._isDeveloping;
            }
            set
            {
                this.OnisDevelopingChanging(value);
                this._isDeveloping = value;
                this.OnisDevelopingChanged();
                this.OnPropertyChanged("isDeveloping");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _isDeveloping;
        partial void OnisDevelopingChanging(global::System.Nullable<bool> value);
        partial void OnisDevelopingChanged();
        /// <summary>
        /// There are no comments for Property isLDC in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> isLDC
        {
            get
            {
                return this._isLDC;
            }
            set
            {
                this.OnisLDCChanging(value);
                this._isLDC = value;
                this.OnisLDCChanged();
                this.OnPropertyChanged("isLDC");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _isLDC;
        partial void OnisLDCChanging(global::System.Nullable<bool> value);
        partial void OnisLDCChanged();
        /// <summary>
        /// There are no comments for Property isSIDS in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> isSIDS
        {
            get
            {
                return this._isSIDS;
            }
            set
            {
                this.OnisSIDSChanging(value);
                this._isSIDS = value;
                this.OnisSIDSChanged();
                this.OnPropertyChanged("isSIDS");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _isSIDS;
        partial void OnisSIDSChanging(global::System.Nullable<bool> value);
        partial void OnisSIDSChanged();
        /// <summary>
        /// There are no comments for Property preferredLanguage in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string preferredLanguage
        {
            get
            {
                return this._preferredLanguage;
            }
            set
            {
                this.OnpreferredLanguageChanging(value);
                this._preferredLanguage = value;
                this.OnpreferredLanguageChanged();
                this.OnPropertyChanged("preferredLanguage");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _preferredLanguage;
        partial void OnpreferredLanguageChanging(string value);
        partial void OnpreferredLanguageChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
