//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 7/26/2016 6:16:50 PM
namespace TreatiesService.Conferences
{
    
    /// <summary>
    /// There are no comments for ConferencesEntities in the schema.
    /// </summary>
    public partial class ConferencesEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new ConferencesEntities object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ConferencesEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "ConferencesModel", "TreatiesService.Conferences");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("TreatiesService.Conferences", global::System.StringComparison.Ordinal))
            {
                return string.Concat("ConferencesModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Meetings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Meetings> Meetings
        {
            get
            {
                if ((this._Meetings == null))
                {
                    this._Meetings = base.CreateQuery<Meetings>("Meetings");
                }
                return this._Meetings;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Meetings> _Meetings;
        /// <summary>
        /// There are no comments for MeetingsGroupeds in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<MeetingsGrouped> MeetingsGroupeds
        {
            get
            {
                if ((this._MeetingsGroupeds == null))
                {
                    this._MeetingsGroupeds = base.CreateQuery<MeetingsGrouped>("MeetingsGroupeds");
                }
                return this._MeetingsGroupeds;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<MeetingsGrouped> _MeetingsGroupeds;
        /// <summary>
        /// There are no comments for Terms in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Terms> Terms
        {
            get
            {
                if ((this._Terms == null))
                {
                    this._Terms = base.CreateQuery<Terms>("Terms");
                }
                return this._Terms;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Terms> _Terms;
        /// <summary>
        /// There are no comments for corr_Conference_Term in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<corr_Conference_Term> corr_Conference_Term
        {
            get
            {
                if ((this._corr_Conference_Term == null))
                {
                    this._corr_Conference_Term = base.CreateQuery<corr_Conference_Term>("corr_Conference_Term");
                }
                return this._corr_Conference_Term;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<corr_Conference_Term> _corr_Conference_Term;
        /// <summary>
        /// There are no comments for Lists in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Lists> Lists
        {
            get
            {
                if ((this._Lists == null))
                {
                    this._Lists = base.CreateQuery<Lists>("Lists");
                }
                return this._Lists;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Lists> _Lists;
        /// <summary>
        /// There are no comments for MeetingTerms in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<MeetingTerms> MeetingTerms
        {
            get
            {
                if ((this._MeetingTerms == null))
                {
                    this._MeetingTerms = base.CreateQuery<MeetingTerms>("MeetingTerms");
                }
                return this._MeetingTerms;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<MeetingTerms> _MeetingTerms;
        /// <summary>
        /// There are no comments for Meetings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMeetings(Meetings meetings)
        {
            base.AddObject("Meetings", meetings);
        }
        /// <summary>
        /// There are no comments for MeetingsGroupeds in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMeetingsGroupeds(MeetingsGrouped meetingsGrouped)
        {
            base.AddObject("MeetingsGroupeds", meetingsGrouped);
        }
        /// <summary>
        /// There are no comments for Terms in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTerms(Terms terms)
        {
            base.AddObject("Terms", terms);
        }
        /// <summary>
        /// There are no comments for corr_Conference_Term in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddTocorr_Conference_Term(corr_Conference_Term corr_Conference_Term)
        {
            base.AddObject("corr_Conference_Term", corr_Conference_Term);
        }
        /// <summary>
        /// There are no comments for Lists in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToLists(Lists lists)
        {
            base.AddObject("Lists", lists);
        }
        /// <summary>
        /// There are no comments for MeetingTerms in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMeetingTerms(MeetingTerms meetingTerms)
        {
            base.AddObject("MeetingTerms", meetingTerms);
        }
    }
    /// <summary>
    /// There are no comments for ConferencesModel.Meetings in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Meetings")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class Meetings : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Meetings object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Meetings CreateMeetings(global::System.Guid ID)
        {
            Meetings meetings = new Meetings();
            meetings.id = ID;
            return meetings;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property url in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string url
        {
            get
            {
                return this._url;
            }
            set
            {
                this.OnurlChanging(value);
                this._url = value;
                this.OnurlChanged();
                this.OnPropertyChanged("url");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _url;
        partial void OnurlChanging(string value);
        partial void OnurlChanged();
        /// <summary>
        /// There are no comments for Property title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string title
        {
            get
            {
                return this._title;
            }
            set
            {
                this.OntitleChanging(value);
                this._title = value;
                this.OntitleChanged();
                this.OnPropertyChanged("title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _title;
        partial void OntitleChanging(string value);
        partial void OntitleChanged();
        /// <summary>
        /// There are no comments for Property description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string description
        {
            get
            {
                return this._description;
            }
            set
            {
                this.OndescriptionChanging(value);
                this._description = value;
                this.OndescriptionChanged();
                this.OnPropertyChanged("description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _description;
        partial void OndescriptionChanging(string value);
        partial void OndescriptionChanged();
        /// <summary>
        /// There are no comments for Property start in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> start
        {
            get
            {
                return this._start;
            }
            set
            {
                this.OnstartChanging(value);
                this._start = value;
                this.OnstartChanged();
                this.OnPropertyChanged("start");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _start;
        partial void OnstartChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnstartChanged();
        /// <summary>
        /// There are no comments for Property end in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> end
        {
            get
            {
                return this._end;
            }
            set
            {
                this.OnendChanging(value);
                this._end = value;
                this.OnendChanged();
                this.OnPropertyChanged("end");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _end;
        partial void OnendChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnendChanged();
        /// <summary>
        /// There are no comments for Property kind in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string kind
        {
            get
            {
                return this._kind;
            }
            set
            {
                this.OnkindChanging(value);
                this._kind = value;
                this.OnkindChanged();
                this.OnPropertyChanged("kind");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _kind;
        partial void OnkindChanging(string value);
        partial void OnkindChanged();
        /// <summary>
        /// There are no comments for Property type in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string type
        {
            get
            {
                return this._type;
            }
            set
            {
                this.OntypeChanging(value);
                this._type = value;
                this.OntypeChanged();
                this.OnPropertyChanged("type");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _type;
        partial void OntypeChanging(string value);
        partial void OntypeChanged();
        /// <summary>
        /// There are no comments for Property access in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string access
        {
            get
            {
                return this._access;
            }
            set
            {
                this.OnaccessChanging(value);
                this._access = value;
                this.OnaccessChanged();
                this.OnPropertyChanged("access");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _access;
        partial void OnaccessChanging(string value);
        partial void OnaccessChanged();
        /// <summary>
        /// There are no comments for Property status in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string status
        {
            get
            {
                return this._status;
            }
            set
            {
                this.OnstatusChanging(value);
                this._status = value;
                this.OnstatusChanged();
                this.OnPropertyChanged("status");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _status;
        partial void OnstatusChanging(string value);
        partial void OnstatusChanged();
        /// <summary>
        /// There are no comments for Property imageUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string imageUrl
        {
            get
            {
                return this._imageUrl;
            }
            set
            {
                this.OnimageUrlChanging(value);
                this._imageUrl = value;
                this.OnimageUrlChanged();
                this.OnPropertyChanged("imageUrl");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _imageUrl;
        partial void OnimageUrlChanging(string value);
        partial void OnimageUrlChanged();
        /// <summary>
        /// There are no comments for Property imageCopyright in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string imageCopyright
        {
            get
            {
                return this._imageCopyright;
            }
            set
            {
                this.OnimageCopyrightChanging(value);
                this._imageCopyright = value;
                this.OnimageCopyrightChanged();
                this.OnPropertyChanged("imageCopyright");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _imageCopyright;
        partial void OnimageCopyrightChanging(string value);
        partial void OnimageCopyrightChanged();
        /// <summary>
        /// There are no comments for Property location in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string location
        {
            get
            {
                return this._location;
            }
            set
            {
                this.OnlocationChanging(value);
                this._location = value;
                this.OnlocationChanged();
                this.OnPropertyChanged("location");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _location;
        partial void OnlocationChanging(string value);
        partial void OnlocationChanged();
        /// <summary>
        /// There are no comments for Property city in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string city
        {
            get
            {
                return this._city;
            }
            set
            {
                this.OncityChanging(value);
                this._city = value;
                this.OncityChanged();
                this.OnPropertyChanged("city");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _city;
        partial void OncityChanging(string value);
        partial void OncityChanged();
        /// <summary>
        /// There are no comments for Property country in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string country
        {
            get
            {
                return this._country;
            }
            set
            {
                this.OncountryChanging(value);
                this._country = value;
                this.OncountryChanged();
                this.OnPropertyChanged("country");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _country;
        partial void OncountryChanging(string value);
        partial void OncountryChanged();
        /// <summary>
        /// There are no comments for Property updated in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> updated
        {
            get
            {
                return this._updated;
            }
            set
            {
                this.OnupdatedChanging(value);
                this._updated = value;
                this.OnupdatedChanged();
                this.OnPropertyChanged("updated");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _updated;
        partial void OnupdatedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnupdatedChanged();
        /// <summary>
        /// There are no comments for Property brs_country in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string brs_country
        {
            get
            {
                return this._brs_country;
            }
            set
            {
                this.Onbrs_countryChanging(value);
                this._brs_country = value;
                this.Onbrs_countryChanged();
                this.OnPropertyChanged("brs_country");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _brs_country;
        partial void Onbrs_countryChanging(string value);
        partial void Onbrs_countryChanged();
        /// <summary>
        /// There are no comments for Property brs_unregion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string brs_unregion
        {
            get
            {
                return this._brs_unregion;
            }
            set
            {
                this.Onbrs_unregionChanging(value);
                this._brs_unregion = value;
                this.Onbrs_unregionChanged();
                this.OnPropertyChanged("brs_unregion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _brs_unregion;
        partial void Onbrs_unregionChanging(string value);
        partial void Onbrs_unregionChanged();
        /// <summary>
        /// There are no comments for Property brs_treaties in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string brs_treaties
        {
            get
            {
                return this._brs_treaties;
            }
            set
            {
                this.Onbrs_treatiesChanging(value);
                this._brs_treaties = value;
                this.Onbrs_treatiesChanged();
                this.OnPropertyChanged("brs_treaties");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _brs_treaties;
        partial void Onbrs_treatiesChanging(string value);
        partial void Onbrs_treatiesChanged();
        /// <summary>
        /// There are no comments for Property brs_terms in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string brs_terms
        {
            get
            {
                return this._brs_terms;
            }
            set
            {
                this.Onbrs_termsChanging(value);
                this._brs_terms = value;
                this.Onbrs_termsChanged();
                this.OnPropertyChanged("brs_terms");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _brs_terms;
        partial void Onbrs_termsChanging(string value);
        partial void Onbrs_termsChanged();
        /// <summary>
        /// There are no comments for Property brs_sessionLanguage in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string brs_sessionLanguage
        {
            get
            {
                return this._brs_sessionLanguage;
            }
            set
            {
                this.Onbrs_sessionLanguageChanging(value);
                this._brs_sessionLanguage = value;
                this.Onbrs_sessionLanguageChanged();
                this.OnPropertyChanged("brs_sessionLanguage");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _brs_sessionLanguage;
        partial void Onbrs_sessionLanguageChanging(string value);
        partial void Onbrs_sessionLanguageChanged();
        /// <summary>
        /// There are no comments for Property brs_linkRegistration in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string brs_linkRegistration
        {
            get
            {
                return this._brs_linkRegistration;
            }
            set
            {
                this.Onbrs_linkRegistrationChanging(value);
                this._brs_linkRegistration = value;
                this.Onbrs_linkRegistrationChanged();
                this.OnPropertyChanged("brs_linkRegistration");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _brs_linkRegistration;
        partial void Onbrs_linkRegistrationChanging(string value);
        partial void Onbrs_linkRegistrationChanged();
        /// <summary>
        /// There are no comments for Property brs_linkFAQ in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string brs_linkFAQ
        {
            get
            {
                return this._brs_linkFAQ;
            }
            set
            {
                this.Onbrs_linkFAQChanging(value);
                this._brs_linkFAQ = value;
                this.Onbrs_linkFAQChanged();
                this.OnPropertyChanged("brs_linkFAQ");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _brs_linkFAQ;
        partial void Onbrs_linkFAQChanging(string value);
        partial void Onbrs_linkFAQChanged();
        /// <summary>
        /// There are no comments for Property brs_linkRecording in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string brs_linkRecording
        {
            get
            {
                return this._brs_linkRecording;
            }
            set
            {
                this.Onbrs_linkRecordingChanging(value);
                this._brs_linkRecording = value;
                this.Onbrs_linkRecordingChanged();
                this.OnPropertyChanged("brs_linkRecording");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _brs_linkRecording;
        partial void Onbrs_linkRecordingChanging(string value);
        partial void Onbrs_linkRecordingChanged();
        /// <summary>
        /// There are no comments for Property brs_organizerId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.Guid> brs_organizerId
        {
            get
            {
                return this._brs_organizerId;
            }
            set
            {
                this.Onbrs_organizerIdChanging(value);
                this._brs_organizerId = value;
                this.Onbrs_organizerIdChanged();
                this.OnPropertyChanged("brs_organizerId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.Guid> _brs_organizerId;
        partial void Onbrs_organizerIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onbrs_organizerIdChanged();
        /// <summary>
        /// There are no comments for Property brs_organizerName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string brs_organizerName
        {
            get
            {
                return this._brs_organizerName;
            }
            set
            {
                this.Onbrs_organizerNameChanging(value);
                this._brs_organizerName = value;
                this.Onbrs_organizerNameChanged();
                this.OnPropertyChanged("brs_organizerName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _brs_organizerName;
        partial void Onbrs_organizerNameChanging(string value);
        partial void Onbrs_organizerNameChanged();
        /// <summary>
        /// There are no comments for Property brs_objectives in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string brs_objectives
        {
            get
            {
                return this._brs_objectives;
            }
            set
            {
                this.Onbrs_objectivesChanging(value);
                this._brs_objectives = value;
                this.Onbrs_objectivesChanged();
                this.OnPropertyChanged("brs_objectives");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _brs_objectives;
        partial void Onbrs_objectivesChanging(string value);
        partial void Onbrs_objectivesChanged();
        /// <summary>
        /// There are no comments for Property brs_infoParticipants in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string brs_infoParticipants
        {
            get
            {
                return this._brs_infoParticipants;
            }
            set
            {
                this.Onbrs_infoParticipantsChanging(value);
                this._brs_infoParticipants = value;
                this.Onbrs_infoParticipantsChanged();
                this.OnPropertyChanged("brs_infoParticipants");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _brs_infoParticipants;
        partial void Onbrs_infoParticipantsChanging(string value);
        partial void Onbrs_infoParticipantsChanged();
        /// <summary>
        /// There are no comments for Property brs_target in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string brs_target
        {
            get
            {
                return this._brs_target;
            }
            set
            {
                this.Onbrs_targetChanging(value);
                this._brs_target = value;
                this.Onbrs_targetChanged();
                this.OnPropertyChanged("brs_target");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _brs_target;
        partial void Onbrs_targetChanging(string value);
        partial void Onbrs_targetChanged();
        /// <summary>
        /// There are no comments for Property brs_agenda in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string brs_agenda
        {
            get
            {
                return this._brs_agenda;
            }
            set
            {
                this.Onbrs_agendaChanging(value);
                this._brs_agenda = value;
                this.Onbrs_agendaChanged();
                this.OnPropertyChanged("brs_agenda");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _brs_agenda;
        partial void Onbrs_agendaChanging(string value);
        partial void Onbrs_agendaChanged();
        /// <summary>
        /// There are no comments for Property brs_background in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string brs_background
        {
            get
            {
                return this._brs_background;
            }
            set
            {
                this.Onbrs_backgroundChanging(value);
                this._brs_background = value;
                this.Onbrs_backgroundChanged();
                this.OnPropertyChanged("brs_background");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _brs_background;
        partial void Onbrs_backgroundChanging(string value);
        partial void Onbrs_backgroundChanged();
        /// <summary>
        /// There are no comments for terms in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<corr_Conference_Term> terms
        {
            get
            {
                return this._terms;
            }
            set
            {
                this._terms = value;
                this.OnPropertyChanged("terms");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<corr_Conference_Term> _terms = new global::System.Data.Services.Client.DataServiceCollection<corr_Conference_Term>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ConferencesModel.MeetingsGrouped in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("MeetingsGroupeds")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class MeetingsGrouped : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new MeetingsGrouped object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static MeetingsGrouped CreateMeetingsGrouped(global::System.Guid ID)
        {
            MeetingsGrouped meetingsGrouped = new MeetingsGrouped();
            meetingsGrouped.id = ID;
            return meetingsGrouped;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property url in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string url
        {
            get
            {
                return this._url;
            }
            set
            {
                this.OnurlChanging(value);
                this._url = value;
                this.OnurlChanged();
                this.OnPropertyChanged("url");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _url;
        partial void OnurlChanging(string value);
        partial void OnurlChanged();
        /// <summary>
        /// There are no comments for Property title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string title
        {
            get
            {
                return this._title;
            }
            set
            {
                this.OntitleChanging(value);
                this._title = value;
                this.OntitleChanged();
                this.OnPropertyChanged("title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _title;
        partial void OntitleChanging(string value);
        partial void OntitleChanged();
        /// <summary>
        /// There are no comments for Property description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string description
        {
            get
            {
                return this._description;
            }
            set
            {
                this.OndescriptionChanging(value);
                this._description = value;
                this.OndescriptionChanged();
                this.OnPropertyChanged("description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _description;
        partial void OndescriptionChanging(string value);
        partial void OndescriptionChanged();
        /// <summary>
        /// There are no comments for Property start in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> start
        {
            get
            {
                return this._start;
            }
            set
            {
                this.OnstartChanging(value);
                this._start = value;
                this.OnstartChanged();
                this.OnPropertyChanged("start");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _start;
        partial void OnstartChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnstartChanged();
        /// <summary>
        /// There are no comments for Property end in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> end
        {
            get
            {
                return this._end;
            }
            set
            {
                this.OnendChanging(value);
                this._end = value;
                this.OnendChanged();
                this.OnPropertyChanged("end");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _end;
        partial void OnendChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnendChanged();
        /// <summary>
        /// There are no comments for Property kind in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string kind
        {
            get
            {
                return this._kind;
            }
            set
            {
                this.OnkindChanging(value);
                this._kind = value;
                this.OnkindChanged();
                this.OnPropertyChanged("kind");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _kind;
        partial void OnkindChanging(string value);
        partial void OnkindChanged();
        /// <summary>
        /// There are no comments for Property type in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string type
        {
            get
            {
                return this._type;
            }
            set
            {
                this.OntypeChanging(value);
                this._type = value;
                this.OntypeChanged();
                this.OnPropertyChanged("type");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _type;
        partial void OntypeChanging(string value);
        partial void OntypeChanged();
        /// <summary>
        /// There are no comments for Property access in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string access
        {
            get
            {
                return this._access;
            }
            set
            {
                this.OnaccessChanging(value);
                this._access = value;
                this.OnaccessChanged();
                this.OnPropertyChanged("access");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _access;
        partial void OnaccessChanging(string value);
        partial void OnaccessChanged();
        /// <summary>
        /// There are no comments for Property status in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string status
        {
            get
            {
                return this._status;
            }
            set
            {
                this.OnstatusChanging(value);
                this._status = value;
                this.OnstatusChanged();
                this.OnPropertyChanged("status");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _status;
        partial void OnstatusChanging(string value);
        partial void OnstatusChanged();
        /// <summary>
        /// There are no comments for Property imageUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string imageUrl
        {
            get
            {
                return this._imageUrl;
            }
            set
            {
                this.OnimageUrlChanging(value);
                this._imageUrl = value;
                this.OnimageUrlChanged();
                this.OnPropertyChanged("imageUrl");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _imageUrl;
        partial void OnimageUrlChanging(string value);
        partial void OnimageUrlChanged();
        /// <summary>
        /// There are no comments for Property imageCopyright in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string imageCopyright
        {
            get
            {
                return this._imageCopyright;
            }
            set
            {
                this.OnimageCopyrightChanging(value);
                this._imageCopyright = value;
                this.OnimageCopyrightChanged();
                this.OnPropertyChanged("imageCopyright");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _imageCopyright;
        partial void OnimageCopyrightChanging(string value);
        partial void OnimageCopyrightChanged();
        /// <summary>
        /// There are no comments for Property location in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string location
        {
            get
            {
                return this._location;
            }
            set
            {
                this.OnlocationChanging(value);
                this._location = value;
                this.OnlocationChanged();
                this.OnPropertyChanged("location");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _location;
        partial void OnlocationChanging(string value);
        partial void OnlocationChanged();
        /// <summary>
        /// There are no comments for Property city in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string city
        {
            get
            {
                return this._city;
            }
            set
            {
                this.OncityChanging(value);
                this._city = value;
                this.OncityChanged();
                this.OnPropertyChanged("city");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _city;
        partial void OncityChanging(string value);
        partial void OncityChanged();
        /// <summary>
        /// There are no comments for Property country in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string country
        {
            get
            {
                return this._country;
            }
            set
            {
                this.OncountryChanging(value);
                this._country = value;
                this.OncountryChanged();
                this.OnPropertyChanged("country");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _country;
        partial void OncountryChanging(string value);
        partial void OncountryChanged();
        /// <summary>
        /// There are no comments for Property updated in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> updated
        {
            get
            {
                return this._updated;
            }
            set
            {
                this.OnupdatedChanging(value);
                this._updated = value;
                this.OnupdatedChanged();
                this.OnPropertyChanged("updated");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _updated;
        partial void OnupdatedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnupdatedChanged();
        /// <summary>
        /// There are no comments for Property brs_country in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string brs_country
        {
            get
            {
                return this._brs_country;
            }
            set
            {
                this.Onbrs_countryChanging(value);
                this._brs_country = value;
                this.Onbrs_countryChanged();
                this.OnPropertyChanged("brs_country");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _brs_country;
        partial void Onbrs_countryChanging(string value);
        partial void Onbrs_countryChanged();
        /// <summary>
        /// There are no comments for Property brs_unregion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string brs_unregion
        {
            get
            {
                return this._brs_unregion;
            }
            set
            {
                this.Onbrs_unregionChanging(value);
                this._brs_unregion = value;
                this.Onbrs_unregionChanged();
                this.OnPropertyChanged("brs_unregion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _brs_unregion;
        partial void Onbrs_unregionChanging(string value);
        partial void Onbrs_unregionChanged();
        /// <summary>
        /// There are no comments for Property brs_treaties in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string brs_treaties
        {
            get
            {
                return this._brs_treaties;
            }
            set
            {
                this.Onbrs_treatiesChanging(value);
                this._brs_treaties = value;
                this.Onbrs_treatiesChanged();
                this.OnPropertyChanged("brs_treaties");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _brs_treaties;
        partial void Onbrs_treatiesChanging(string value);
        partial void Onbrs_treatiesChanged();
        /// <summary>
        /// There are no comments for Property brs_terms in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string brs_terms
        {
            get
            {
                return this._brs_terms;
            }
            set
            {
                this.Onbrs_termsChanging(value);
                this._brs_terms = value;
                this.Onbrs_termsChanged();
                this.OnPropertyChanged("brs_terms");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _brs_terms;
        partial void Onbrs_termsChanging(string value);
        partial void Onbrs_termsChanged();
        /// <summary>
        /// There are no comments for Property brs_sessionLanguage in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string brs_sessionLanguage
        {
            get
            {
                return this._brs_sessionLanguage;
            }
            set
            {
                this.Onbrs_sessionLanguageChanging(value);
                this._brs_sessionLanguage = value;
                this.Onbrs_sessionLanguageChanged();
                this.OnPropertyChanged("brs_sessionLanguage");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _brs_sessionLanguage;
        partial void Onbrs_sessionLanguageChanging(string value);
        partial void Onbrs_sessionLanguageChanged();
        /// <summary>
        /// There are no comments for Property brs_linkRegistration in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string brs_linkRegistration
        {
            get
            {
                return this._brs_linkRegistration;
            }
            set
            {
                this.Onbrs_linkRegistrationChanging(value);
                this._brs_linkRegistration = value;
                this.Onbrs_linkRegistrationChanged();
                this.OnPropertyChanged("brs_linkRegistration");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _brs_linkRegistration;
        partial void Onbrs_linkRegistrationChanging(string value);
        partial void Onbrs_linkRegistrationChanged();
        /// <summary>
        /// There are no comments for Property brs_linkFAQ in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string brs_linkFAQ
        {
            get
            {
                return this._brs_linkFAQ;
            }
            set
            {
                this.Onbrs_linkFAQChanging(value);
                this._brs_linkFAQ = value;
                this.Onbrs_linkFAQChanged();
                this.OnPropertyChanged("brs_linkFAQ");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _brs_linkFAQ;
        partial void Onbrs_linkFAQChanging(string value);
        partial void Onbrs_linkFAQChanged();
        /// <summary>
        /// There are no comments for Property brs_linkRecording in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string brs_linkRecording
        {
            get
            {
                return this._brs_linkRecording;
            }
            set
            {
                this.Onbrs_linkRecordingChanging(value);
                this._brs_linkRecording = value;
                this.Onbrs_linkRecordingChanged();
                this.OnPropertyChanged("brs_linkRecording");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _brs_linkRecording;
        partial void Onbrs_linkRecordingChanging(string value);
        partial void Onbrs_linkRecordingChanged();
        /// <summary>
        /// There are no comments for terms in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<corr_Conference_Term> terms
        {
            get
            {
                return this._terms;
            }
            set
            {
                this._terms = value;
                this.OnPropertyChanged("terms");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<corr_Conference_Term> _terms = new global::System.Data.Services.Client.DataServiceCollection<corr_Conference_Term>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ConferencesModel.Terms in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Terms")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class Terms : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Terms object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Terms CreateTerms(global::System.Guid ID)
        {
            Terms terms = new Terms();
            terms.id = ID;
            return terms;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this._name = value;
                this.OnnameChanged();
                this.OnPropertyChanged("name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// There are no comments for Property description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string description
        {
            get
            {
                return this._description;
            }
            set
            {
                this.OndescriptionChanging(value);
                this._description = value;
                this.OndescriptionChanged();
                this.OnPropertyChanged("description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _description;
        partial void OndescriptionChanging(string value);
        partial void OndescriptionChanged();
        /// <summary>
        /// There are no comments for Property synonyms in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string synonyms
        {
            get
            {
                return this._synonyms;
            }
            set
            {
                this.OnsynonymsChanging(value);
                this._synonyms = value;
                this.OnsynonymsChanged();
                this.OnPropertyChanged("synonyms");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _synonyms;
        partial void OnsynonymsChanging(string value);
        partial void OnsynonymsChanged();
        /// <summary>
        /// There are no comments for Property informeaTerm in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string informeaTerm
        {
            get
            {
                return this._informeaTerm;
            }
            set
            {
                this.OninformeaTermChanging(value);
                this._informeaTerm = value;
                this.OninformeaTermChanged();
                this.OnPropertyChanged("informeaTerm");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _informeaTerm;
        partial void OninformeaTermChanging(string value);
        partial void OninformeaTermChanged();
        /// <summary>
        /// There are no comments for Property parentNames in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string parentNames
        {
            get
            {
                return this._parentNames;
            }
            set
            {
                this.OnparentNamesChanging(value);
                this._parentNames = value;
                this.OnparentNamesChanged();
                this.OnPropertyChanged("parentNames");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _parentNames;
        partial void OnparentNamesChanging(string value);
        partial void OnparentNamesChanged();
        /// <summary>
        /// There are no comments for Property parentIds in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string parentIds
        {
            get
            {
                return this._parentIds;
            }
            set
            {
                this.OnparentIdsChanging(value);
                this._parentIds = value;
                this.OnparentIdsChanged();
                this.OnPropertyChanged("parentIds");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _parentIds;
        partial void OnparentIdsChanging(string value);
        partial void OnparentIdsChanged();
        /// <summary>
        /// There are no comments for meetings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<corr_Conference_Term> meetings
        {
            get
            {
                return this._meetings;
            }
            set
            {
                this._meetings = value;
                this.OnPropertyChanged("meetings");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<corr_Conference_Term> _meetings = new global::System.Data.Services.Client.DataServiceCollection<corr_Conference_Term>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ConferencesModel.corr_Conference_Term in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("corr_Conference_Term")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class corr_Conference_Term : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new corr_Conference_Term object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        /// <param name="conferenceId">Initial value of conferenceId.</param>
        /// <param name="termId">Initial value of termId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static corr_Conference_Term Createcorr_Conference_Term(global::System.Guid ID, global::System.Guid conferenceId, global::System.Guid termId)
        {
            corr_Conference_Term corr_Conference_Term = new corr_Conference_Term();
            corr_Conference_Term.id = ID;
            corr_Conference_Term.conferenceId = conferenceId;
            corr_Conference_Term.termId = termId;
            return corr_Conference_Term;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property VersionNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] VersionNumber
        {
            get
            {
                if ((this._VersionNumber != null))
                {
                    return ((byte[])(this._VersionNumber.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnVersionNumberChanging(value);
                this._VersionNumber = value;
                this.OnVersionNumberChanged();
                this.OnPropertyChanged("VersionNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _VersionNumber;
        partial void OnVersionNumberChanging(byte[] value);
        partial void OnVersionNumberChanged();
        /// <summary>
        /// There are no comments for Property conferenceId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid conferenceId
        {
            get
            {
                return this._conferenceId;
            }
            set
            {
                this.OnconferenceIdChanging(value);
                this._conferenceId = value;
                this.OnconferenceIdChanged();
                this.OnPropertyChanged("conferenceId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _conferenceId;
        partial void OnconferenceIdChanging(global::System.Guid value);
        partial void OnconferenceIdChanged();
        /// <summary>
        /// There are no comments for Property termId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid termId
        {
            get
            {
                return this._termId;
            }
            set
            {
                this.OntermIdChanging(value);
                this._termId = value;
                this.OntermIdChanged();
                this.OnPropertyChanged("termId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _termId;
        partial void OntermIdChanging(global::System.Guid value);
        partial void OntermIdChanged();
        /// <summary>
        /// There are no comments for Meeting in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Meetings Meeting
        {
            get
            {
                return this._Meeting;
            }
            set
            {
                this._Meeting = value;
                this.OnPropertyChanged("Meeting");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Meetings _Meeting;
        /// <summary>
        /// There are no comments for Term in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Terms Term
        {
            get
            {
                return this._Term;
            }
            set
            {
                this._Term = value;
                this.OnPropertyChanged("Term");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Terms _Term;
        /// <summary>
        /// There are no comments for meetingsGrouped in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public MeetingsGrouped meetingsGrouped
        {
            get
            {
                return this._meetingsGrouped;
            }
            set
            {
                this._meetingsGrouped = value;
                this.OnPropertyChanged("meetingsGrouped");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private MeetingsGrouped _meetingsGrouped;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ConferencesModel.Lists in the schema.
    /// </summary>
    /// <KeyProperties>
    /// LocalizedLabelId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Lists")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("LocalizedLabelId")]
    public partial class Lists : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Lists object.
        /// </summary>
        /// <param name="value">Initial value of value.</param>
        /// <param name="localizedLabelId">Initial value of LocalizedLabelId.</param>
        /// <param name="optionSetId">Initial value of optionSetId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Lists CreateLists(int value, global::System.Guid localizedLabelId, global::System.Guid optionSetId)
        {
            Lists lists = new Lists();
            lists.value = value;
            lists.LocalizedLabelId = localizedLabelId;
            lists.optionSetId = optionSetId;
            return lists;
        }
        /// <summary>
        /// There are no comments for Property value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int value
        {
            get
            {
                return this._value;
            }
            set
            {
                this.OnvalueChanging(value);
                this._value = value;
                this.OnvalueChanged();
                this.OnPropertyChanged("value");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _value;
        partial void OnvalueChanging(int value);
        partial void OnvalueChanged();
        /// <summary>
        /// There are no comments for Property label in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string label
        {
            get
            {
                return this._label;
            }
            set
            {
                this.OnlabelChanging(value);
                this._label = value;
                this.OnlabelChanged();
                this.OnPropertyChanged("label");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _label;
        partial void OnlabelChanging(string value);
        partial void OnlabelChanged();
        /// <summary>
        /// There are no comments for Property LocalizedLabelId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid LocalizedLabelId
        {
            get
            {
                return this._LocalizedLabelId;
            }
            set
            {
                this.OnLocalizedLabelIdChanging(value);
                this._LocalizedLabelId = value;
                this.OnLocalizedLabelIdChanged();
                this.OnPropertyChanged("LocalizedLabelId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _LocalizedLabelId;
        partial void OnLocalizedLabelIdChanging(global::System.Guid value);
        partial void OnLocalizedLabelIdChanged();
        /// <summary>
        /// There are no comments for Property optionSetId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid optionSetId
        {
            get
            {
                return this._optionSetId;
            }
            set
            {
                this.OnoptionSetIdChanging(value);
                this._optionSetId = value;
                this.OnoptionSetIdChanged();
                this.OnPropertyChanged("optionSetId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _optionSetId;
        partial void OnoptionSetIdChanging(global::System.Guid value);
        partial void OnoptionSetIdChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ConferencesModel.MeetingTerms in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("MeetingTerms")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class MeetingTerms : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new MeetingTerms object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static MeetingTerms CreateMeetingTerms(global::System.Guid ID)
        {
            MeetingTerms meetingTerms = new MeetingTerms();
            meetingTerms.id = ID;
            return meetingTerms;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this._name = value;
                this.OnnameChanged();
                this.OnPropertyChanged("name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// There are no comments for Property parentNames in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string parentNames
        {
            get
            {
                return this._parentNames;
            }
            set
            {
                this.OnparentNamesChanging(value);
                this._parentNames = value;
                this.OnparentNamesChanged();
                this.OnPropertyChanged("parentNames");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _parentNames;
        partial void OnparentNamesChanging(string value);
        partial void OnparentNamesChanged();
        /// <summary>
        /// There are no comments for Property parentIds in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string parentIds
        {
            get
            {
                return this._parentIds;
            }
            set
            {
                this.OnparentIdsChanging(value);
                this._parentIds = value;
                this.OnparentIdsChanged();
                this.OnPropertyChanged("parentIds");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _parentIds;
        partial void OnparentIdsChanging(string value);
        partial void OnparentIdsChanged();
        /// <summary>
        /// There are no comments for Property webinarCount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> webinarCount
        {
            get
            {
                return this._webinarCount;
            }
            set
            {
                this.OnwebinarCountChanging(value);
                this._webinarCount = value;
                this.OnwebinarCountChanged();
                this.OnPropertyChanged("webinarCount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _webinarCount;
        partial void OnwebinarCountChanging(global::System.Nullable<int> value);
        partial void OnwebinarCountChanged();
        /// <summary>
        /// There are no comments for Property workshopCount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> workshopCount
        {
            get
            {
                return this._workshopCount;
            }
            set
            {
                this.OnworkshopCountChanging(value);
                this._workshopCount = value;
                this.OnworkshopCountChanged();
                this.OnPropertyChanged("workshopCount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _workshopCount;
        partial void OnworkshopCountChanging(global::System.Nullable<int> value);
        partial void OnworkshopCountChanged();
        /// <summary>
        /// There are no comments for Property egCount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> egCount
        {
            get
            {
                return this._egCount;
            }
            set
            {
                this.OnegCountChanging(value);
                this._egCount = value;
                this.OnegCountChanged();
                this.OnPropertyChanged("egCount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _egCount;
        partial void OnegCountChanging(global::System.Nullable<int> value);
        partial void OnegCountChanged();
        /// <summary>
        /// There are no comments for Property ahgCount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> ahgCount
        {
            get
            {
                return this._ahgCount;
            }
            set
            {
                this.OnahgCountChanging(value);
                this._ahgCount = value;
                this.OnahgCountChanged();
                this.OnPropertyChanged("ahgCount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _ahgCount;
        partial void OnahgCountChanging(global::System.Nullable<int> value);
        partial void OnahgCountChanged();
        /// <summary>
        /// There are no comments for Property symposiaCount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> symposiaCount
        {
            get
            {
                return this._symposiaCount;
            }
            set
            {
                this.OnsymposiaCountChanging(value);
                this._symposiaCount = value;
                this.OnsymposiaCountChanged();
                this.OnPropertyChanged("symposiaCount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _symposiaCount;
        partial void OnsymposiaCountChanging(global::System.Nullable<int> value);
        partial void OnsymposiaCountChanged();
        /// <summary>
        /// There are no comments for Property confCount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> confCount
        {
            get
            {
                return this._confCount;
            }
            set
            {
                this.OnconfCountChanging(value);
                this._confCount = value;
                this.OnconfCountChanged();
                this.OnPropertyChanged("confCount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _confCount;
        partial void OnconfCountChanging(global::System.Nullable<int> value);
        partial void OnconfCountChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
